services:
  - type: web
    name: onepass3d
    runtime: python
    plan: free
    buildCommand: python -m pip install --upgrade pip && python -m pip install --only-binary=:all: -r requirements.txt
    startCommand: python run.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.11"
